### ISSUE TITLE
Add static device definitions

### ISSUE THREAD

**Issue by cdjackson** [openhab/org.openhab.binding.zigbee#101]
Currently the binding produces things completely dynamically by reading the device supported clusters, and the supported commands and attributes within these clusters. This allows devices to be supported with no definition.

It does however have some limitations in that device specific features can't be supported, and additional information can't be included. Therefore static thing definitions should be supported to either override the static definitions, or supplement them.

**Comment by cdjackson** [comment]
See #100

**Comment by weakfl** [comment]
Subscribing to receive emails (already subscribed to repo, so I have to answer here)...
