### ISSUE TITLE
Unit tests not run by maven (as testSourceDirectory incorrectly configured)

### ISSUE THREAD

**Issue by hsudbrock** [openhab/org.openhab.binding.zigbee#144]
In the `pom.xml`, the source directory for the tests is configured as `<testSourceDirectory>src/test</testSourceDirectory>`, although the unit tests are actually in directory `src/main/test`. In consequence, the maven build will not run any unit tests.

Besides that, would it be sensible to move the unit tests to `/src/test/java`, to align with default maven directory layout?

**Comment by kaikreuzer** [comment]
You are right, this is somehow messed up - the tests are actually currently in "src/main/test", while they should be in "src/test/java" instead. And then the "testSourceDirectory" entry could be removed from the pom.xml completely.

**Comment by hsudbrock** [comment]
I will create a short PR for this (including a small change for making all tests pass again), so we can discuss in the PR if the changes for this small cleanup are the right ones.
