### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by tavalin** [openhab/org.openhab.binding.zigbee#150]
Hi Chris

Commit https://github.com/openhab/org.openhab.binding.zigbee/commit/ac176d7a6716069c92d630f84496ecdab3f09d10 removed the THING_PROPERTY_PERMITJOINING constant from ZigBeeBindingConstants - not sure if this was deliberate or not - but there are usages of the constant in other classes so the mvn build currently fails.

**Comment by cdjackson** [comment]
Damn. I was working on two different PRs and the removal of the use of the constant seems to be in the other one.

**Comment by kaikreuzer** [comment]
@cdjackson I have now added you to the build notifications so that you notice it yourself when a build that you triggered fails :-)

**Comment by cdjackson** [comment]
Thanks. I wonder if PR builds are not configured on this repo as there was no failure on the PR itself before merging...

**Comment by cdjackson** [comment]
@kaikreuzer I've added CI in travis to verify PRs - I'd not noticed this wasn't configured already...

**Comment by kaikreuzer** [comment]
Ah, that explains. I was just trying to do the same and was wondering that it was already there, but only 5 times executed. No wonder when you just only had it set up - thanks :-)
