### ISSUE TITLE
Add support for Develco han-interface - power meter readings

### ISSUE THREAD

**Issue by coandersen** [openhab/org.openhab.binding.zigbee#164]
In Norway there will be installed 700 000+ power meters which gives owners access to real-time power consumption. Develco has developed a Zigbee-device which accesses the HAN-interface of the power meter. 

If possible I would like support for the device to be added to the Zigbee binding. Especially these attributes:

Id# | Name | Type | Man |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
0x0305 | TotalReactivePower | Int32 | O |   |   |   |  
0x0304 | TotalActivePower | Int32 | O |   |   |   |  
0x0505 | RMSVoltagePhA | Uint16 | O | L1 | - | Volts | (V)
0x0508 | RMSCurrentPhA | Uint16 | O | L1 | - | Amps | (A)

[emizb-132-technical-manual-emi-norwegian-han.pdf](https://github.com/openhab/org.openhab.binding.zigbee/files/1794391/emizb-132-technical-manual-emi-norwegian-han.pdf)

**Comment by cdjackson** [comment]
Any feedback on this?

**Comment by coandersen** [comment]
Sorry, did not see this before now. Does this mean my device is supported by the binding? If so I will test it soon.

**Comment by linuxtrap** [comment]
Hello
Did you continue work with this cdjackson? Would be nice with some Power readings to :)
