### ISSUE TITLE
Some configuration parameters cannot be updated

### ISSUE THREAD

**Issue by hsudbrock** [openhab/org.openhab.binding.zigbee#186]
UIs for Eclipse SmartHome (like, e.g., PaperUI) permit to update the configuration parameters of ZigBee dongles (including properties regarding the serial connection like serial port, baud rate, or flow control). This results in a call to `ZigBeeCoordinatorHandler#handleConfigurationUpdate` with the new configuration. This method currently ignores several configuration parameters. When updating the configuration with PaperUI for a Telegesis dongle, the following parameters are ignored: port, baud, initialize, channel, password, panid, and extendedpanid).

As a result, in the UI one can see the changed configuration parameters, but they have not been applied in the ZigBee binding.

**Comment by cdjackson** [comment]
I will take a look at this soon, but they should be applied if the binding restarts, so this is a workaround until I provide the update.
