### ISSUE TITLE
After restart of the OSGi runtime things are sometimes offline or they cannot control the devices anymore

### ISSUE THREAD

**Issue by TomTravaglino** [openhab/org.openhab.binding.zigbee#193]
During the tests of the Ember SPI implementation we observed that after restarting the OSGi runtime the things and items were not longer usable/reachable. They fall in one of these two possible states:

State 1:
- Things still exist and they all are online (it takes >1 minute until all things are online).
- Items exist but their states are 'NULL'. It is possible to set their states (via PaperUI) but they don't have any effect on the devices. Means: the state of the item is updated but on the device nothing happens.

State 2:
- Things still exist but they're offline. The status is "Status=OFFLINE: Node is not found on network". Even after several minutes the things didn't turn online.

**Comment by cdjackson** [comment]
Please provide a logfile showing the issue.

**Comment by TomTravaglino** [comment]
Here are the logs produced by the restart. At the end the things were in the status described in "State 2"

[logs.txt](https://github.com/openhab/org.openhab.binding.zigbee/files/1959644/logs.txt)

**Comment by cdjackson** [comment]
The issue is that the network is down. The bridge should be offline - I assume that's not what you see though?

**Comment by TomTravaglino** [comment]
The bridge was online. Here is the list of the things and their status.

zigbee:coordinator_ember:internal (Type=Bridge, Status=ONLINE, Label=ZigBee (internal), Bridge=null)
zigbee:device:internal:00124b0008aaf089 (Type=Thing, Status=OFFLINE: Node is not found on network, Label=Bitron Home 902010/21B, Bridge=zigbee:coordinator_ember:internal)
zigbee:device:internal:00124b000420a2b5 (Type=Thing, Status=OFFLINE: Node is not found on network, Label=Bitron Home 902010/25, Bridge=zigbee:coordinator_ember:internal)
zigbee:device:internal:00124b0002ce33ff (Type=Thing, Status=OFFLINE: Node is not found on network, Label=Bitron Home 902010/26, Bridge=zigbee:coordinator_ember:internal)

**Comment by hsudbrock** [comment]
@TomTravaglino Due to the age of this issue - is this still relevant, or can it be closed?

**Comment by TomTravaglino** [comment]
Oh yes, this one is quite aged. Let's close it.
