### ISSUE TITLE
Device is not discovered again after deleting the corresponding thing

### ISSUE THREAD

**Issue by TomTravaglino** [openhab/org.openhab.binding.zigbee#194]
Often when you delete a thing then these two possible behaviors were observed
- It's not possible to pair the device again because it's not discovered by the scan
- The device can be paired but it doesn't turn online

The issue is not reliably reproducable. Sometimes it helps to restart the runtime and sometimes even this step doesn't help.
After deleting the network status file the device could be discovered again. Not sure if this really fixed it but it helped during my tests.

**Comment by cdjackson** [comment]
Please provide a logfile showing the issue.

**Comment by cdjackson** [comment]
This issue seems to conflict with #190

**Comment by TomTravaglino** [comment]
So, I reproduced it. What i did:
- Pair successfully a device
- Remove the thing
- Restart the runtime
- Try to pair it again --> Failed

I attached the logs starting with the moment when the zigbee bundles were started and network initialized. At 2018-04-30_10:16:24:244 I started the first attempt to pair the device.

[logs.txt](https://github.com/openhab/org.openhab.binding.zigbee/files/1959950/logs.txt)

**Comment by cdjackson** [comment]
In all cases in this log, the network appears to be offline - this would explain why joining doesn't work.

![image](https://user-images.githubusercontent.com/1041475/40811835-cdb6e544-652a-11e8-85b1-f7f530fe4d90.png)

**Comment by cdjackson** [comment]
This seems to be the same as #193 - network is offline.

**Comment by flashbac2** [comment]
> In all cases in this log, the network appears to be offline - this would explain why joining doesn't work.
> 
> ![image](https://user-images.githubusercontent.com/1041475/40811835-cdb6e544-652a-11e8-85b1-f7f530fe4d90.png)

What tool did you use to parse the log file that way? It would make troubleshooting so much easier...

**Comment by cdjackson** [comment]
https://www.cd-jackson.com/index.php/openhab/zigbee-log-viewer
