### ISSUE TITLE
Creation of bridge for Telegesis dongle fails very often

### ISSUE THREAD

**Issue by TomTravaglino** [openhab/org.openhab.binding.zigbee#198]
Very often the creation of the bridge for the Telegesis dongle ends up with the bridge staying in status OFFLINE or UNKNOWN. Most times when you then restart the ZigBee bundles the bridge goes ONLINE.

[logs-create-telegesis-failed.txt](https://github.com/openhab/org.openhab.binding.zigbee/files/1978656/logs-create-telegesis-failed.txt)
[logs-create-telegesis-failed-and-online-after-restart.txt](https://github.com/openhab/org.openhab.binding.zigbee/files/1978658/logs-create-telegesis-failed-and-online-after-restart.txt)

**Comment by cdjackson** [comment]
I'm not sure I understand the issue. Are you saying that when starting the binding first time, it often doesn't work, but restarting normally works?

The first log it looks like the dongle did not respond.

The second log I'm not sure what you're reporting? Can you please describe the problem as it seems to me that everything is working and the network is up, and the dongle is online.

**Comment by TomTravaglino** [comment]
> Are you saying that when starting the binding first time, it often doesn't work, but restarting normally works?

No. It's not about starting the binding for the first time. What I meant is: when I create the bridge it stays in status OFFLINE or UNKNOWN. Then if I restart the bundles the bridge is ONLINE. Now if I delete the bridge and create it again I will very likely face the issue again.

> The second log I'm not sure what you're reporting ... it seems to me that everything is working and the network is up, and the dongle is online.

The second log shows that the bridge was OFFLINE after is was created and it was ONLINE after restarting the bundles.
Check line 51 & 53 of the log file. There you can seen that the status of the bridge is reported as OFFLINE.
From line 54 on you can see that I restarted the bundles and that at the end the bridge was ONLINE

**Comment by cdjackson** [comment]
Ok, I missed that. The second log is the same as the first - the dongle did not respond to the first command sent.

I've never seen this in the past, and no-one using openHAB has reported it, so I'm wondering if it's specific to your system somehow? We could add a retry mechanism to resend the initialisation commands if they fail, but that's about all that I can suggest.

**Comment by cdjackson** [comment]
https://github.com/zsmartsystems/com.zsmartsystems.zigbee/pull/305 Merged.

**Comment by TomTravaglino** [comment]
@cdjackson Your change seems to have made the bridge creation more stable. At least my quick tests were successful

**Comment by cdjackson** [comment]
Thanks @TomTravaglino - let's give it a day or so and see how it looks, then we can close this (hopefully) if it looks resolved...

**Comment by cdjackson** [comment]
As above - I assume this is closed.
