### ISSUE TITLE
Discovery of devices fails often when using Telegesis and Ember dongle

### ISSUE THREAD

**Issue by TomTravaglino** [openhab/org.openhab.binding.zigbee#199]
This issue was mostly observed after deleting things and trying to discover the devices again. When you restart the scan (several times) the devices are discovered again.
Is this issue possibly related to #194 ?

[logs-ember-discover-devices-failed-and-found-after-rescan.txt](https://github.com/openhab/org.openhab.binding.zigbee/files/1978820/logs-ember-discover-devices-failed-and-found-after-rescan.txt)

**Comment by cdjackson** [comment]
What does this log show? It looks fine - is this showing a successful join or is there something specific you're trying to show?

If devices are not joining, then you will likely need to look at a sniffer. If there is nothing at all in the log showing that the coordinator has seen the device, then the binding can't do anything.

**Comment by TomTravaglino** [comment]
I investigated the issue in detail and it turned out that there is an issue on our side. In some situations the invocation of the discovery doesn't happen. So we can close this.
