### ISSUE TITLE
Xbee XStick Light Link Devices (hue)

### ISSUE THREAD

**Issue by otaviojr** [openhab/org.openhab.binding.zigbee#266]
I've been trying OH2 with XBee Xstick device, and found it can not handle Philips hue bulbs. They joins the network, but, all messages fails. OH2 is unable to discovery the device.

Looking for the problem I endup at XBee driver. I notice zsmartsystems driver will handle the stick.

Looking at their code I notice they will enforce APS encryption on XBee devices.

Since light Link Devices do not share the same link key, it will fail.

I go further and changed their code to disable APS encryption and my hue bulbs started to work seamless.

I opened an issue at zsmartsystems's GitHub, but, this is affecting OH2, so, I'm opening this here.

https://github.com/zsmartsystems/com.zsmartsystems.zigbee/issues/400

Sorry, if it is at the wrong place. But, other people could have the same issue with XBee and hue bulbs/light Link Devices.

regards

**Comment by cdjackson** [comment]
Thanks. I will close this as this is not configured in the binding.
