### ISSUE TITLE
Add Option to disable the onboard LEDs

### ISSUE THREAD

**Issue by LennartPl** [openhab/org.openhab.binding.zigbee#299]
Add Option to disable the onboard LEDs. Referring to zigbee2mqtt it is possible to disable these LEDs. If you have your stick not in an black box the bright LED is very disturbing.

Found the Command in [openhab/zigbee](https://github.com/openhab/zigbee/blob/bb0947304f2bc5bf41a44013c7e6008c16120d6d/zigbee-cc2531/src/main/java/org/eclipse/smarthome/zigbee/dongle/cc2531/network/packet/ZToolCMD.java#L522) but I'm not incorporated to implement this.

**Comment by cdjackson** [comment]
I guess that this is related to the TI chipset, although you don’t really say?

In any case, this would require changes to the driver first before anything could be considered with the binding. Please feel free to provide a PR for the driver -:

https://github.com/zsmartsystems/com.zsmartsystems.zigbee.

**Comment by cdjackson** [comment]
As above, this needs to be addressed in the libraries.
