### ISSUE TITLE
CC2531 End device can't get multiple channels in Openhab

### ISSUE THREAD

**Issue by amarpulli544** [openhab/org.openhab.binding.zigbee#306]
Hello Everyone,
I would like to introduce my own end device in cc2531. I had configured cc2531 device as a coordinator and end device. When i was looking for my end device in paper ui,it got discovered with Unknown Zigbee Device.I successfully added to the things my end device. After few seconds the device going to ONLINE state.But here i'm getting only one channel like below

![p3](https://user-images.githubusercontent.com/16384828/48883362-7e110980-ee45-11e8-86a3-95cc47a24851.png).

What can I do for getting multiple channels like dimmer and color and switch in paper ui.
Thanks and Regards,
Amar.

**Comment by cdjackson** [comment]
The binding will detect the clusters that your device is supporting. If you only support the OnOff cluster, then you will only get OnOff channel. You will need to implement other clusters to get the other channels.

As we discussed previously, I would suggest to discuss your issues on the TI forum as implementing an end device isn't really the focus of this repo. I can also recommend reading the ZigBee specification, and the ZigBee Cluster Specification, although as you use the TI chipset, you need to understand their tools when implementing these clusters.
