### ISSUE TITLE
ZigBeeCoordinatorHandler must not use bundleContext

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/org.openhab.binding.zigbee#31]
The `bundleContext` field will be removed from the BaseThingHandler at some point in time and it is not intended to be used by bindings.
The ZigBeeCoordinatorHandler uses it in order to register a discovery service. This must be changed to registering it in the handler factory instead as it is e.g. done in the Hue binding (and many others) as well.

**Comment by cdjackson** [comment]
Yep - I did see this come up recently - I'll take a look at Hue - thanks.
