### ISSUE TITLE
Color tempterature converter uses cold for high values, warm for low values (but should be vice versa)

### ISSUE THREAD

**Issue by hsudbrock** [openhab/org.openhab.binding.zigbee#313]
In ESH, for the color temperature channel '0% should be the coldest setting (highest Kelvin value)' (see (cf. https://www.eclipse.org/smarthome/documentation/development/bindings/thing-definition.html)).

In the ZigBee binding, this is reversed (0% is the lowest Kelvin value, 100% is the highest Kelvin value).

Maybe this was introduced by my PR https://github.com/openhab/org.openhab.binding.zigbee/pull/287 (for some bulbs - as the goal of that PR was to align how the converter behaves for bulbs that provide min/max Mired values, and for bulbs that do not provide min/max Mired values).

I plan to prepare a fix for this soon. If I overlook a reason why this should be the other way round for this binding, I would be happy about a ping, otherwise I will prepare a (probably small) PR to change this.

**Comment by cdjackson** [comment]
I see there are now system channels available for this, so I guess it would be worth changing the channel name to use the system channel at the same time?

**Comment by hsudbrock** [comment]
Sounds good.

Am 30. November 2018 15:59:09 MEZ schrieb Chris Jackson <notifications@github.com>:
>I see there are now system channels available for this, so I guess it
>would be worth changing the channel name to use the system channel at
>the same time?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openhab/org.openhab.binding.zigbee/issues/313#issuecomment-443229125

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
