### ISSUE TITLE
Add support for Xiaomi Aqara Sensor HT via static thing definition XML

### ISSUE THREAD

**Issue by puzzle-star** [openhab/org.openhab.binding.zigbee#314]
Add support for Xiaomi Aqara Sensor HT via static thing definition XML (the round temperature and humidity sensor, not the square one, which correctly reports its clusters)

Pull Request: Add support for Xiaomi Aqara Sensor HT via static thing definition XML (issue #314) (Pull Request #317)

Pedro

**Comment by puzzle-star** [comment]
> I am opening this issue to reference to it when sending the pull request with the XML and the discovery.txt updates.

**Comment by cdjackson** [comment]
Closed by #317
