### ISSUE TITLE
Wrong command send to level_control channel

### ISSUE THREAD

**Issue by Hambootje** [openhab/org.openhab.binding.zigbee#316]
I want a switch and a dimmer for manual control of my lightbulb. If I link the level_control channel to both a switch and a dimmer item, the bulb turn on to 100% level by the switch.
The wanted behaviour is that the bulb is switched on to the last level before is was switched off.

I have defined 2 items as shown below, both linked to the Levelcontrol channel of a tradfri lightbulb.
The switch sends ON/OFF, the dimmer 0-100.
The ON command from the switch sets the lightbulb to 100% level. However, this is not represented by the dimmer item.

`Switch Werkkamer_Lamp      "Werkkamer Lamp [%s]" [ "Lighting" ]`    
`Dimmer Werkkamer_Lamp_dim    "Werkkamer Dim [%d %%]" [ "Lighting" ]`

According Chris: 

> This should not be the case. If I remember correctly, when the OnOff command is sent to a level_control channel, it should send the same command as when it’s sent to the switch channel.

> I checked, and you are right that different commands are used. Please raise an issue for this and I’ll have a look at it when I get a chance.

### Configuration
Coordinator | Ember EM35x or CC2531EMK
openHAB version | 2.4.0.SNAPSHOT
Hardware | Raspberry Pi 3+
Java version | openjdk version "1.8.0_152"
Devices | zigbee:device:013C1ADE:000b57fffe909e96:000B57FFFE909E96_1_dimmer

**Comment by cdjackson** [comment]
This should now be resolved. If there's any issues, please reopen or open another issue.
