### ISSUE TITLE
Add suport for the FAN_CONTROL cluster

### ISSUE THREAD

**Issue by layttan** [openhab/org.openhab.binding.zigbee#358]
The zigbee binding currently doesn't support the FAN_CONTROL (0x0202 ?) cluster needed by Hampton Bay (King Of Fans) controllers sold by home depot.

Example zigbee xml can be found
https://drive.google.com/open?id=1wrY0BoXVNy44LiGUK7g1pvD-tncRZq0Z

**Comment by cdjackson** [comment]
Features added in https://github.com/zsmartsystems/com.zsmartsystems.zigbee/pull/527

It will still be a while before this makes it into the OH binding.
