### ISSUE TITLE
No handling for transaction timeout

### ISSUE THREAD

**Issue by TomTravaglino** [openhab/org.openhab.binding.zigbee#371]
I investigated what happens when you try to remove a battery operated device. When the device is not reachable the `ManagementLeaveRequest` runs into a timeout. But then in `ZigBeeNetworkManager ` there is no special handling for this timeout. It just produces a log entry reporting the status code of the response.
Now you're working on improving the transaction management (branch [transaction-queue](https://github.com/zsmartsystems/com.zsmartsystems.zigbee/tree/transaction-queue)). I took a look at it and as far as I could see transaction timeouts don't seem to play any role there. Will timeouts get a specific handling in future or will they just be considered as a normal failed transaction?

**Comment by cdjackson** [comment]
Timeouts will be retried once or twice, and then will be handled as a failed transaction. I'm not sure what you are suggesting as an alternative?

**Comment by hsudbrock** [comment]
@TomTravaglino Does @cdjackson's comment above answer your question, so that this issue can be closed?

**Comment by TomTravaglino** [comment]
@hsudbrock Thanks for reminding me of this issue. I think we can close this as the answer was given.
