### ISSUE TITLE
ZigBeeDiscoveryService uses deprecated ExtendedDiscoveryService API 

### ISSUE THREAD

**Issue by hanneshofmann** [openhab/org.openhab.binding.zigbee#390]
I just stumbled upon the `ZigBeeDiscoveryService` and noticed that it makes use of the deprecated `ExtendedDiscoveryService` API. 

So far I understood, the API has been marked as deprecated because the `Inbox` is already able to deal with incremental discovery result updates. Furthermore the `ZigBeeDiscoveryService` uses only `DiscoveryServiceCallback#getExistingDiscoveryResult` method which default implementation always returns null. Therefore, the behaviour of the `ZigBeeDiscoveryService` shall remain unchanged when removing the API.

Perhaps I have overlooked something, @cdjackson?  If you have no objection on the removal of this API, I would like to provide a follow-up PR.

**Comment by cdjackson** [comment]
It can be removed.

The extended service was added and used to allow the bindings to find out about things in the inbox, but this caused problems and was removed recently in ESH. It now returns null so does nothing.

Thanks.
