### ISSUE TITLE
Speedup discovery by reading multiple attributes with single request

### ISSUE THREAD

**Issue by hsudbrock** [openhab/org.openhab.binding.zigbee#399]
Currently, when discovering a new device, the discovery queries several attributes each with a single `Read Attribute` command (see [here](https://github.com/openhab/org.openhab.binding.zigbee/blob/0cd602d8e4e9b675a63e9a9bfbe20c35ee99e9dd/org.openhab.binding.zigbee/src/main/java/org/openhab/binding/zigbee/discovery/ZigBeeNodePropertyDiscoverer.java#L80)).

Since recently, the ZSS ZigBee library supports reading multiple attributes with a single request (see [here](https://github.com/zsmartsystems/com.zsmartsystems.zigbee/pull/530)).

It would be nice to use this feature for speeding up the discovery process by requesting all the attributes at once (with a fallback to using multiple `Read Attribute` requests for devices that cannot put all attribute values into a single response).

I could implement this, @cdjackson - so in case you already started with this please give me a ping :)

**Comment by cdjackson** [comment]
I've not looked at implementing this in the property discoverer - but have started implemented the same thing in the polling consolidation...

Feel free to implement - I hope to get the new transaction manager merged in the coming days and will then do an update for the OH TP with these features.

**Comment by hsudbrock** [comment]
Sounds good, I will implement this then...
