### ISSUE TITLE
Build fails due to checkstyle issue (after recent bump of sat-plugin to 0.6.1 in openhab pom)

### ISSUE THREAD

**Issue by hsudbrock** [openhab/org.openhab.binding.zigbee#420]
The checkstyle issue can be seen, e.g., in this build: https://ci.openhab.org/job/PR-org.openhab.binding.zigbee/568/consoleFull (which is not for `master` branch, but it is reproducible on `master` branch as well).

The error message is: `Failed to execute goal org.openhab.tools.sat:sat-plugin:0.6.1:checkstyle (default) on project org.openhab.binding.zigbee: Unable to execute mojo: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: Failed during checkstyle configuration: unable to parse configuration stream: Property ${checkstyle.forbiddenPackageUsageCheck.forbiddenPackages} has not been set`.

This is probably not ass issue for most other bindings, as for the `openhab-addons` project such checkstyle properties are set (here: https://github.com/openhab/openhab2-addons/blob/master/tools/checkstyle.properties).

**Comment by hsudbrock** [comment]
I will have another look this afternoon to see what needs to be done here. (Or are you maybe already investigating this, @cdjackson ?)

**Comment by hsudbrock** [comment]
The following PR for the `static-code-analysis` project should resolve the issue: https://github.com/openhab/static-code-analysis/pull/329 However, it is quite some months old, and I don't know if it is intended to be merged...

**Comment by cdjackson** [comment]
There was a PR on the ZWave binding from @wbourn yesterday that I think has fixed the problem with ZWave. As CI is running very slowly (ie it's taking 6 or 7 hours) it takes a long time to ru and can time outn, but it did pass in the end.

**Comment by cdjackson** [comment]
See https://github.com/openhab/org.openhab.binding.zwave/pull/1158

**Comment by hsudbrock** [comment]
Thanks for the pointer, Chris. As a quick fix, we could do a similar thing as for the Z-Wave binding. But: The approach used for Z-Wave is note 100% ideal for the ZigBee binding, because we have a multi-module project, and referencing the checkstyle config from the top-level pom will prevent building successfully from within a submodule.

There might be workarounds (like the one here described for checkstyle: https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/multi-module-config.html), but I haven't checked those yet.

**Comment by cdjackson** [comment]
I’ve not looked at how this is done in the openhab repo, but isn’t there the same issue there with multiple modules?

Sorry for the hassle with this - it was changed in openhab without any notification to maintainers - if you have a proposal to resolve it, it would be great?

**Comment by hsudbrock** [comment]
I had hoped to get feedback on the non-merged PR from the code analysis project. I will create a PR for the binding pom (maybe today, probably tomorrow) as I did not get any feedback...
