### ISSUE TITLE
Channel converter for 'Current Summation Delivered' attribute in SmartEnergy Metering cluster

### ISSUE THREAD

**Issue by TomTravaglino** [openhab/org.openhab.binding.zigbee#426]
In contrast to #410 where @hsudbrock suggests to enhance the `ZigBeeConverterMeasurementPower` to also provide the instantaneous power consumption from the SE MeteringCluster this issue is about providing only the **summed** power consumption.

I want to implement a converter for the attribute `Current Summation Delivered` to get the summed energy consumption of a device. Since the attribute `Current Summation Delivered` provides values for energy, gas and water I plan to first create a specific channel type for the summed energy consumption. Later the channels types for water and gas can follow. The separation is necessary as the quantity types and the categories can be different.

The channel type could look like this
```
	<!-- Smart Energy - Metering: Current Summation Delivered for Electric Metering -->
	<channel-type id="electric_metering_current_summation_delivered">
        <item-type>Number:Power</item-type>
		<label>...</label>
		<description>...</description>
		<category>Energy</category>
        <state pattern="%.1f %unit%" readOnly="true" />
	</channel-type>
```

Regarding the converter,
- The name could be `ZigBeeConverterMeteringCurrentSummationDelivered`
- It would create a channel depending on the cluster attribute `MeteringDeviceType`. The differentiation would allow to create channels for energy (see channel type above), water and gas.
- It would update the channel state with a QuantityType depending on the cluster attribute `UnitOfMeasure` which in case of energy should be 'kWh'. The differentiation would allow to provide a QantityType for energy (see channel type above), water and gas.

**Comment by cdjackson** [comment]
This channel was added already.
