### ISSUE TITLE
Accessing remote serial port

### ISSUE THREAD

**Issue by mikomarrache** [openhab/org.openhab.binding.zigbee#460]
Does this binding support access to a remote serial port (RFC2217 like)?

I was looking at the code (_ZigBeeSerialPort.java_) and I saw that _gnu.io.*_ is used directly without any reference to _gnu.io.rfc2217.TelnetSerialPort_.

Does that mean the binding only support local serial port? Is there a reason why _org.eclipse.smarthome.io.transport.serial.*_ is not used?

**Comment by cdjackson** [comment]
No - this is not supported by the binding at this time.
