### ISSUE TITLE
Xiaomi Aqara Temperature and Humidity Sensor no information

### ISSUE THREAD

**Issue by baum1234** [openhab/org.openhab.binding.zigbee#539]
Currently I'm trying to connect the Xiaomi Aqara Temperature and Humidity Sensor (the square ones) to my openHAB.

openHab finds the sensor without problems, but it only connects after a long time (about 3 minutes). It also finds channels (Temperature, Atmospheric Pressure, Humidity).

Till now it sounds okay. But I don't receive any information about Temperature, Atmospheric Pressure and Humidity. But I get this information through zigbee2mqtt.

I could post the debug information, but there is so many information, I don't know which is important.

**Comment by cdjackson** [comment]
Please discuss questions like this on the openHAB community support forum.  Thanks.
