### ISSUE TITLE
Coordinator properties are missing in Paper UI since 2.5 M2

### ISSUE THREAD

**Issue by marfrh** [openhab/org.openhab.binding.zigbee#545]
### Outline
In a clean install of openHAB 2.5 (no upgrade), zigbee coordinator properties in Paper UI are missing coordinator firmware version and other properties (see screenshot below). This could also be reproduced for 2.5 M2 and 2.5 M3. For the affected openHAB versions, coordinator properties only consist of "usb_product_id" and "usb_vendor_id". Other properties (e.g. firmware version) are not visible.  Example:
![Coordinator_1](https://user-images.githubusercontent.com/51024599/71713443-154add80-2e0a-11ea-8325-453b6d86fdf8.png)

Properties of other non-coordinator-zigbee-devices do not seem to be affected.

### How it should look like:
Up to openHAB 2.5 M1, a lot more information was shown. Example:

![Coordinator_2](https://user-images.githubusercontent.com/51024599/71713548-783c7480-2e0a-11ea-9ad7-6b9b727802a7.png)

### Additional information
I'm not a java developer, but nevertheless I tried to find the root of this problem by comparing how properties are updated for nodes and coordinators, as it seems to work fine for nodes.
- Nodes: PROPERTY_FIRMWARE_VERSION is being detected once in "ZigBeeNodePropertyDiscoverer" and in case of an OTA upgrade in "ZigBeeThingHandler".
Other properties are being updated through "nodeUpdated(node)".
- Coordinator: PROPERTY_FIRMWARE_VERSION is determined in function "initialiseZigBee" and in function "nodeUpdated()". Other properties (wich are also missing) are only detected in function "nodeUpdated()".

So I suspect that either
A) "nodeUpdated" does not get called for coordinators --> issue might be wrong here and more related to com.zsmartsystems.zigbee?
or
B) "nodeUpdated" does get called for coordinators and properties are present, but these are not displayed in Paper UI

### Configuration

| Configuration    | Description                                                                    |
|------------------|--------------------------------------------------------------------------------|
| Coordinator used | Ember and Telegesis Dongle |
| openHAB version  | 2.5 M2 and greater, including 2.5 stable |
| Hardware         | Raspberry PI 3B |
| Memory           | 1GB |
| Java version     | Java 8 (openJDK 1.8.0_222 |
| Devices          | - |

### Logs
Not available.

**Comment by cdjackson** [comment]
I have fixed this already and it is included in the latest updates.
