### ISSUE TITLE
Bitronvideo 2010/34 worked with version 2.5.0, but fails in 2.5.1

### ISSUE THREAD

**Issue by wkochFPV** [openhab/org.openhab.binding.zigbee#557]
Bitronvideo 2010/34 scene switch worked with:
Openhab2 version 2.5.0 with Zigbee binding and ember coordinator, bitronvideo zigbee usb stick

but fails with (button presses not resulting in events, not processed by rules)

2.5.1-1 and 2.5.1-2 versions

with message
"Unsupported local server cluster 0005" in openhab.log when pressing button.

**Comment by cdjackson** [comment]
I'll make a change to hopefully fix this shortly. Please let me know in the coming days if it is fixed.

**Comment by wkochFPV** [comment]
Thank you, your patch fixed the problem!!!!

**Comment by cdjackson** [comment]
Thanks.
