### ISSUE TITLE
Adding enhanced support for Xiaomi/Aqara Curtain Motor

### ISSUE THREAD

**Issue by robotronnn** [openhab/org.openhab.binding.zigbee#565]
So far it's only possible to toggle the motor to either close or open the curtain.
Would be lovely if you could integrate the missing channels.
Thanks for the binding!

![image](https://user-images.githubusercontent.com/35403887/78036377-826b0200-736a-11ea-860f-ce7b0dd8d0b4.png)

**Comment by cdjackson** [comment]
> Would be lovely if you could integrate the missing channels.

What channels are missing though? I don't have the device, so I've no idea what this supports. If you are able to add the functions, then please do. If you want to send me a device then I will take a look.

**Comment by cdjackson** [comment]
Closing this. If there is further information available describing what is required, then please provide as requested earlier and re-open.
