### ISSUE TITLE
Xiaomi MiJia Smart Wireless Switch - OFFLINE Node has not completed discovery

### ISSUE THREAD

**Issue by tomasbad** [openhab/org.openhab.binding.zigbee#580]
I have openHAB 2.5.5 Release Build, Zigbee binding with CC2531 Coordinator. With Xiaomi Mi Temperature and Humidity Sensor work it fine.
If I am trying bind Xiaomi MiJia Smart Wireless Switch, in thePaper UI->Thing show message "OFFLINE Node has not completed discovery".

I found something in issue #428 about upgrading to a newer version of the libraries, but I need more info about it.

---
203 x Active  x  80 x 2.5.5.202005130327      x org.openhab.binding.zigbee
296 x Active  x  80 x 1.3.4                   x com.zsmartsystems.zigbee
297 x Active  x  80 x 1.3.3                   x com.zsmartsystems.zigbee.console
298 x Active  x  80 x 1.3.4                   x com.zsmartsystems.zigbee.console.ember
299 x Active  x  80 x 1.3.3                   x com.zsmartsystems.zigbee.dongle.cc2531
300 x Active  x  80 x 1.3.3                   x com.zsmartsystems.zigbee.dongle.ember
301 x Active  x  80 x 1.3.4                   x com.zsmartsystems.zigbee.dongle.telegesis
302 x Active  x  80 x 1.3.4                   x com.zsmartsystems.zigbee.dongle.xbee
303 x Active  x  80 x 2.5.5                   x org.openhab.binding.zigbee
304 x Active  x  80 x 2.5.5                   x org.openhab.binding.zigbee.cc2531
305 x Active  x  80 x 2.5.5                   x org.openhab.binding.zigbee.console
306 x Active  x  80 x 2.5.5                   x org.openhab.binding.zigbee.console.ember
307 x Active  x  80 x 2.5.5                   x org.openhab.binding.zigbee.ember
308 x Active  x  80 x 2.5.5                   x org.openhab.binding.zigbee.telegesis
309 x Active  x  80 x 2.5.5                   x org.openhab.binding.zigbee.xbee

Configuration | Description

Coordinator used | CC2531
openHAB version | 2.5.5
Hardware | Raspberry Pi 4
Memory | 4Gb
Java version | 1.8.0_252
Devices | Xiaomi MiJia Smart Wireless Switch

### Logs
[openhab.log](https://github.com/openhab/org.openhab.binding.zigbee/files/4701875/openhab.log)

**Comment by cdjackson** [comment]
I don't think you're reporting a bug here, so I'd suggest that it's best if you discuss this on the community support forum.  I had a quick look through the log, but there's not a lot to go on.  Xiaomi devices need to be kept awake during discovery.

Please discuss on the community forum where there is more support available with people using these devices (hopefully). This issue list is really to resolve bugs.
