### ISSUE TITLE
Only perform discovery on existing devices

### ISSUE THREAD

**Issue by cdjackson** [openhab/org.openhab.binding.zigbee#583]
Currently the binding performs discovery on all devices - even those that are already `Things`. This is because the discovery service has no way to know if a device is already discovered and added as a `Thing`.

Since devices may (re)join the network at any time we either need to add devices when discovery is started, or add support for the OH background discovery concept.

We also need to handle one other case which is if Things are deleted, but not removed from the network. In this case, if we don't add all known things during discovery, we will loose devices completely.

**Comment by falmanna** [comment]
Does it make sense to check on the existing things using `thingRegistery` when discovering existing devices after starting a scan?
```
if (node.getNetworkAddress() == 0 || thingRegistry.stream().anyMatch(thing -> thing.getUID().toString()
      .toLowerCase().trim().contains(node.getIeeeAddress().toString().toLowerCase().trim()))) {
      continue;
}
```
I've made this change and it seems to be working, but I am not sure if I missed something as I have little knowledge about the internals of the ZigBee binding.

**Comment by cdjackson** [comment]
It's not allowed for the discovery service to interface with the thingRegistry. This is what we used to have in the past, but it was removed some time ago.

**Comment by cdjackson** [comment]
Sorry - to be clearer - what I meant was this was originally part of ESH - I think it was called the "extended discovery service" and this feature was removed from the core a while back.
