### ISSUE TITLE
rfc2217 support (cc2531, others ?)

### ISSUE THREAD

**Issue by gerwsx** [openhab/org.openhab.binding.zigbee#609]
openHAB 2.5.9 Release Build with small patch (see forum thread).

The serial port stays connected using rfc2217 after suppressing “Unsupported comm operation” exception, but initialization of cc2531 is failing.

https://community.openhab.org/t/solved-zwave-zigbee-rfc2217-remote-serial-port-howto/81633/89

**Comment by cdjackson** [comment]
In general RFC2217 support should be handled outside the binding - that was the reason to add the ESH serial abstraction layer. If you have a PR that can solve any niggles in the binding with the way the serial abstraction is interfaced, then I'm happy to look at that, but at the moment this issue isn't really something that I think is a binding issue.

**Comment by gerwsx** [comment]
It would be an improvement, I think, to include the small patch I posted in the thread on the openhab forum (catch the UnsupportedCommOperationException). Interesting to see if other zigbee sticks also have initialization problems.

**Comment by cdjackson** [comment]
If you want to propose an PR, then please do so.

**Comment by gerwsx** [comment]
Thanks for the quick reply. I don't have the code anymore since I switched to Conbee2 (deConz). It's a really small change, feel free to include with another change.
