### ISSUE TITLE
Unhandled exceptions during bunding init (OH3)

### ISSUE THREAD

**Issue by kpanchen** [openhab/org.openhab.binding.zigbee#660]
Updated to OH+binding 3.1.0. Unhandled exceptions on binding startup / things discovery. Seems fine after, no crashes.

[zigbee_log.txt](https://github.com/openhab/org.openhab.binding.zigbee/files/6730736/zigbee_log.txt)

Let me know if debug logging would require.

**Comment by cdjackson** [comment]
Please provide debug logging for this, and also advise what the devices are that might be causing this.

**Comment by kpanchen** [comment]
> Please provide debug logging for this, and also advise what the devices are that might be causing this.

[openhab.log](https://github.com/openhab/org.openhab.binding.zigbee/files/6731185/openhab.log)

Devices are just five sengled E21-N13A bulbs, all the same in the same location. Not added as a thing at the moment.
![things](https://user-images.githubusercontent.com/43836896/123748702-8b56c600-d882-11eb-97ae-4bea065a29be.png)

Thanks!

**Comment by cdjackson** [comment]
Unfortunately I can't really see what is happening with this. There must be an attribute that is incorrectly cast. Normally this happens if a device has an attribute configured incorrectly. The library tries to normalise such things, but there's always the possibility that there's one I've not covered. Unfortunately the log doesn't show this as there's no communications with the device.

I'd suggest to remove the XML for the device (in the "userdata / bridge name" folder) and then start discovery again and see if we can log the issue.

**Comment by kpanchen** [comment]
> Unfortunately I can't really see what is happening with this. There must be an attribute that is incorrectly cast. Normally this happens if a device has an attribute configured incorrectly. The library tries to normalise such things, but there's always the possibility that there's one I've not covered. Unfortunately the log doesn't show this as there's no communications with the device.
> 
> I'd suggest to remove the XML for the device (in the "userdata / bridge name" folder) and then start discovery again and see if we can log the issue.

[openhab.log](https://github.com/openhab/org.openhab.binding.zigbee/files/6731955/openhab.log)
This time all five detected fine:

![things2](https://user-images.githubusercontent.com/43836896/123768204-1ee5c200-d896-11eb-9f4f-7743c0a769b9.png)

**Comment by cdjackson** [comment]
I really need to see the full debug logs to understand what is happening. Please take a look at the binding documentation on how to configure this - currently there is no zigbee information being logged, and as the error is in the zigbee framework it's not possible to see what's happening if this isn't enabled.

**Comment by cdjackson** [comment]
This should be fixed with #662
