### ISSUE TITLE
Hue lamps stop working because channels cannot be initialized

### ISSUE THREAD

**Issue by yuergen** [openhab/org.openhab.binding.zigbee#683]
### Outline
I have six Hue lamps within my house that were working perfectly for the last ~two years. For some reason, that I am unable to identify, I now cannot control the lamps anymore. The reason seems to be that the zigbee-_dimmer channel fails to initialize.

I have tested this with openHAB 3.1.0, upgraded to 3.2.0M3 and then downgraded to 3.0.2 with no changes in behavior.
The ZigBee devices show zigbee_device_initialised=true and are shown as online in the Things-Settings. If I remove power from the devices and wait some time they fall back to unknown or offline.

I have also switched from a Telegesis/Qivicon ZigBee-USB-Interface to an Ember powered Smabit AV2010/10. To version control the settings I now configure the coordinator via a .things file. Please see below.

While testing, retrying and also changing the ZigBee coordinator, I reset the Lamps multiple times via a Philips remote. If I remove them, then the process of joining them via openHAB's inbox seems to work flawlessly.

I am happy to provide more details and do testing, however I need pointers on what to do.

### Configuration

| Configuration    | Description                                                                    |
|------------------|--------------------------------------------------------------------------------|
| Coordinator used |     Smabit AV2010/10                       |
| openHAB version  | ( 3.1.0, upgraded to 3.2.0M3 and then downgraded to 3.0.2    |
| Hardware         |     x86, i3-4160T                                                  |
| Memory           |    8GB                                                                           |
| Java version     |     openjdk 11.0.12 2021-07-20 LTS, zulu11-jre-headless                  |
| Devices          | EgWohnzimmerTischlampe_Temp     zigbee:device:013E70B9:001788010452280f \\ EgWohnzimmerStehlampe_Temp      zigbee:device:013E70B9:001788010859cca0 \\ EgWohnzimmerStehlampeSofa_Temp  zigbee:device:013E70B9:001788010856df32 \\ EgGarderobeLampe_ColorTemp      zigbee:device:013E70B9:0017880104501cd0    |

### Logs
I have used the following logging settings to gain the attached log files:
```
log:set DEBUG org.openhab.binding.zigbee
log:set DEBUG com.zsmartsystems.zigbee
log:set DEBUG com.zsmartsystems.zigbee.dongle.ember.internal.ash
```

I have saved the log file to gist: (https://gist.github.com/yuergen/d34ac1a683f5ea4633476bbccad4add7)

**Comment by cdjackson** [comment]
I'll close this. If there's any further questions, please discuss on the forum or reopen this.
