### ISSUE TITLE
deconz binding connection failures.

### ISSUE THREAD

**Issue by thales-man** [openhab/org.openhab.binding.zigbee#739]
<img width="804" alt="Screenshot 2022-02-21 at 12 00 52 pm" src="https://user-images.githubusercontent.com/17850586/154953751-51d8b751-0691-424f-8ada-f4e478fb4ebb.png">

I'm getting this 2/3 times a week, it happens randomly. i've reported this before to no avail. apparently 'works for me' is a sufficient answer. so sensible questions only please and i will endeavour to obtain the information you want in order to identify where the problem is.

what i can tell you is, this is on OH3.2.1. it was recently upgraded and didn't happen before. i've seen signs of the IP address changing (10 addresses which i don't use locally) but this has NOT happened on more recent breaks. pausing and restarting the service after reconfirming the IP address re-initialises the service.

**Comment by cdjackson** [comment]
This issue list is for the zigbee binding - not the deconz binding. I think the deconz binding is part of oh-addons.
